name: deploy
on:
  push:
    branches:
      - main


jobs:
  deploy-to-app-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:

    # Checkout current branch
    - uses: 'actions/checkout@v3'

    # Authenticate via Service Account Key JSON
    # See https://github.com/google-github-actions/auth#authenticating-via-service-account-key-json-1
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    # Use Google official GHA to deploy 🎉
    #- id: 'deploy'
      #uses: 'google-github-actions/deploy-appengine@v1'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE_URI="${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_PROJECT_ENV }}:latest"
        docker build -t "$IMAGE_URI" .
        docker push "$IMAGE_URI"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_PROJECT_ENV  }}  \
        --image "${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_PROJECT_ENV  }}:latest" \
        --platform managed \
        --region ${{ secrets.GCP_LOCATION }} \
        --port 8080 \
        --memory 512Mi \
        --cpu 1 \
        --max-instances 1 \
        --project ${{ secrets.GCP_PROJECT_ID  }} \
        --service-account ${{ secrets.GCP_KEY }} \
        --set-env-vars MY_ENV=${{ secrets.GCP_PROJECT_ENV }}
